version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: $DATABASE_URL
      DEBUG: $DEBUG

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            source venv/bin/activate
            python backend/manage.py test

  build-and-push:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Print Docker Tag
          command: echo "Building Docker image $DOCKERHUB_USERNAME/quiz-app:latest"
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/quiz-app:latest .
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Image to DockerHub
          command: |
            docker push $DOCKERHUB_USERNAME/quiz-app:latest

  deploy-to-ec2:
    docker:
      - image: circleci/python:3.9
    steps:
      - run:
          name: Print Private Key
          command: echo "Private Key $EC2_PRIVATE_KEY"
      - run:
          name: Deploy to EC2
          command: |
            echo "$EC2_PRIVATE_KEY" > private_key.pem
            chmod 600 private_key.pem
            ssh -o StrictHostKeyChecking=no -i private_key.pem -t ec2-user@$EC2_PUBLIC_IP \<< EOF
            # Commands to execute on EC2
            docker pull pranay2406/quiz-app:latest
            docker run -d -p 8000:8000 pranay2406/quiz-app:latest
            EOF


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
      - deploy-to-ec2:
          requires:
            - build-and-push
