# Generated by Django 5.1.6 on 2025-02-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_quizattempt_unique_quiz_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
