# Generated by Django 5.1.6 on 2025-02-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_quizattempt_score_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
