# Generated by Django 5.1.6 on 2025-04-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_quiz_title'),
    ]

    operations = [
    ]
